### PR TITLE
Rebuild for gcc7 and so on, bump version

### PR DESCRIPTION
**Pull request by dpryan79**
This builds locally for Linux, not sure about the other platforms.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Not sure why this isn't testing on windows, I set it to not be skipped.

**Comment by dpryan79** [comment]
@sodre @bgruening One of you want to take a look? The location of libjvm.so changes with openjdk releases, so I've pinned to one of them.

**Comment by bgruening** [comment]
@dpryan79 I think the `fn` can be removed other than that it looks good. No clue about windows. Thanks for fixing this recipe.

**Comment by dpryan79** [comment]
@bgruening Thanks, I hadn't even noticed the `fn`, guess it was legacy. I've removed it now.

**Comment by dpryan79** [comment]
@bgruening This is good to go now.

**Pull request merged**
