### PR TITLE
add patch to help find libjvm

### PR DESCRIPTION
**Pull request by rvalieris**
builds here have failed for R 3.4.1.

I am adding a patch from https://github.com/AnacondaRecipes/r-rjava-feedstock, that helps finding the libjvm.
I tested this on the linux-anvil image and it seems to work.

credits for the patch goes to @mingwandroid

### CODE REVIEW

**Comment by mingwandroid** [comment]
Cool, but I'd really prefer to make my own PRs for my work, once `conda-forge` adopts our compilers and `conda-build 3`.

**Comment by rvalieris** [comment]
I understand, sorry. I saw your commits on the anaconda repo, but I wasn't sure if you were going to merge those changes back here.
in this case, I rather wait for your PR.

**Comment by mingwandroid** [comment]
No, I didn't mean to delete it, conda-forge are not yet using conda-build 3 nor our compilers but in the meantime it's fine for you to merge across my fixes as you find them, it's just a lot more difficult and less efficient for someone other than myself to submit my work.

Please go ahead.

**Comment by rvalieris** [comment]
doh I completely misunderstood !  well in that case

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
@rvalieris @mingwandroid I will close this maybe we can work on https://github.com/conda-forge/r-rjava-feedstock/pull/3

**Pull request closed without merging**
