### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Merge from AnacondaRecipes

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@mariusvniekerk do you know why the openjdk package is not working and we need the yum packages?

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
This should have been taken care of in #7

**Pull request closed without merging**
